site_name: My Wiki
site_url: https://adi14041999.github.io/my_wiki/
site_description: A personal wiki for notes, ideas, and projects.
use_directory_urls: true

nav:
  - Home: index.md
  - AI:
    - Deep Learning for Computer Vision:
      - Introduction: ai/deep_learning_for_computer_vision/introduction.md
      - Image Classification with Linear Classifiers: ai/deep_learning_for_computer_vision/image_classification_with_linear_classifiers.md
      - Regularization: ai/deep_learning_for_computer_vision/regularization.md
      - Optimization: ai/deep_learning_for_computer_vision/optimization.md
      - Backpropagation: ai/deep_learning_for_computer_vision/backpropagation.md
      - Backpropagation for a Linear Layer: ai/deep_learning_for_computer_vision/backpropagation_for_a_linear_layer.md
      - Neural Networks- Setting up the Architecture: ai/deep_learning_for_computer_vision/neural_networks_setting_up_the_architecture.md
      - Neural Networks- Setting up the Data: ai/deep_learning_for_computer_vision/neural_networks_setting_up_the_data.md
      - Neural Networks- Learning and Evaluation: ai/deep_learning_for_computer_vision/neural_networks_learning_and_evaluation.md
      - Putting it together- Minimal Neural Network Case Study: ai/deep_learning_for_computer_vision/putting_it_together_minimal_neural_network_case_study.md
      - Convolutional Neural Networks- Architectures, Convolution / Pooling Layers: ai/deep_learning_for_computer_vision/convolutional_neural_networks_architectures_convolution_pooling_layers.md
      - A review of RNNs and Transformers: ai/deep_learning_for_computer_vision/a_review_of_rnns_and_transformers.md
      - Self-Supervised Learning: ai/deep_learning_for_computer_vision/self_supervised_learning.md
      - A review of Generative Models: ai/deep_learning_for_computer_vision/a_review_of_generative_models.md
    - Natural Language Processing:
      - Introduction: ai/natural_language_processing/introduction.md
      - Representing words: ai/natural_language_processing/representing_words.md
      - SVD based methods: ai/natural_language_processing/svd_based_methods.md
      - Distributional semantics and Word2vec: ai/natural_language_processing/distributional_semantics_and_word2vec.md
      - Language Models: ai/natural_language_processing/language_models.md
      - Recurrent Neural Networks: ai/natural_language_processing/recurrent_neural_networks.md
      - Gated Recurrent Units (GRUs): ai/natural_language_processing/gated_recurrent_units.md
      - Long-Short Term Memory (LSTM) Networks: ai/natural_language_processing/long_short_term_memory_networks.md
      - Seq2Seq Models: ai/natural_language_processing/seq2seq_models.md
      - Attention Mechanism: ai/natural_language_processing/attention_mechanism.md
      - How large language models work, a visual intro to transformers: ai/natural_language_processing/how_large_language_models_work_a_visual_intro_to_transformers.md
      - Attention in transformers, visually explained: ai/natural_language_processing/attention_in_transformers_visually_explained.md
      - The basic Transformer: ai/natural_language_processing/the_basic_transformer.md
      - Decoder-only Transformers: ai/natural_language_processing/decoder_only_transformers.md
      - Differences between the basic Transformer and the Decoder-Only Transformer: ai/natural_language_processing/differences_between_the_basic_transformer_and_the_decoder_only_transformer.md
      - Self-Attention and Transformers, a mathematical approach: ai/natural_language_processing/self_attention_and_transformers_a_mathematical_approach.md
    - Deep Generative Models:
      - Introduction: ai/deep_generative_models/introduction.md
      - Autoregressive Models: ai/deep_generative_models/autoregressive_models.md
      - Variational Autoencoders: ai/deep_generative_models/variational_autoencoders.md
      - Normalizing flow models: ai/deep_generative_models/normalizing_flow_models.md
      - Recap at this point: ai/deep_generative_models/recap_at_this_point.md
      - Generative Adversarial Networks: ai/deep_generative_models/generative_adversarial_networks.md
      - Energy Based Models: ai/deep_generative_models/energy_based_models.md
      - Score Based Models: ai/deep_generative_models/score_based_models.md
      - Score Based Generative Modeling: ai/deep_generative_models/score_based_generative_modeling.md
      - Evaluating Generative Models: ai/deep_generative_models/evaluating_generative_models.md
      - Diffusion Models from an image generation perspective: ai/deep_generative_models/diffusion_models_from_an_image_generation_perspective.md
      - Score Based Diffusion Models: ai/deep_generative_models/score_based_diffusion_models.md
  - Math:
    - Foundational Math:
      - The Quadratic Formula: math/foundational_math/the_quadratic_formula.md
      - Trigonometry fundamentals: math/foundational_math/trigonometry_fundamentals.md
      - Fundamentals of Complex Numbers: math/foundational_math/fundamentals_of_complex_numbers.md
    - Linear Algebra:
      - Vectors, vector addition, and scalar multiplication: math/linear_algebra/vectors_vector_addition_and_scalar_multiplication.md
      - Vector geometry in Rn and correlation coefficients: math/linear_algebra/vector_geometry_in_mathbb_r_n_and_correlation_coefficients.md
      - Planes in R3: math/linear_algebra/planes_in_r3.md
      - Span, subspaces, and dimension: math/linear_algebra/span_subspaces_and_dimension.md
      - Basis and orthogonality: math/linear_algebra/basis_and_orthogonality.md
      - Projections: math/linear_algebra/projections.md
      - Applications of projections in Rn- orthogonal bases of planes and linear regression: math/linear_algebra/applications_of_projections_in_rn_orthogonal_bases_of_planes_and_linear_regression.md
    - Probability:
      - Probability and Counting: math/probability/probability_and_counting.md
      - Story Proofs and Axioms of Probability: math/probability/story_proofs_and_axioms_of_probability.md
      - Conditional Probability: math/probability/conditional_probability.md
      - Some famous problems: math/probability/some_famous_problems.md
      - Random Variables: math/probability/random_variables.md
      - Expectation: math/probability/expectation.md
      - Indicator Random Variables: math/probability/indicator_random_variables.md
      - Poisson Distribution: math/probability/poisson_distribution.md
      - Continuous Distributions: math/probability/continuous_distributions.md
      - Normal Distribution: math/probability/normal_distribution.md
      - Exponential Distribution: math/probability/exponential_distribution.md
      - Joint Distributions: math/probability/joint_distributions.md
      - Independence of Random Variables: math/probability/independence_of_random_variables.md
      - Conditional Distributions: math/probability/conditional_distributions.md
      - Multinomial Distribution: math/probability/multinomial_distribution.md
      - Covariance and Correlation: math/probability/covariance_and_correlation.md
      - Transformations of Random Variables: math/probability/transformations_of_random_variables.md
      - Convolution: math/probability/convolution.md
      - Beta Distributions: math/probability/beta_distributions.md
      - Conditional Expectation: math/probability/conditional_expectation.md
      - Jensen's inequality: math/probability/jensens_inequality.md
      - Central Limit Theorem: math/probability/central_limit_theorem.md
      - Multivariate Normal Distribution: math/probability/multivariate_normal_distribution.md
      - Markov Chains: math/probability/markov_chains.md
    - Multivariate Calculus:
      - The TL;DR version of Derivatives: math/multivariate_calculus/the_tl_dr_version_of_derivatives.md
      - Multivariable functions, level sets, and contour plots: math/multivariate_calculus/multivariable_functions_level_sets_and_contour_plots.md
  - Productivity:
    - How to Build Your Career in AI:
      - Three Steps to Career Growth: productivity/how_to_build_your_career_in_ai/three_steps_to_career_growth.md
      - Phase 1- Learning: productivity/how_to_build_your_career_in_ai/phase_1_learning.md
      - Phase 2- Projects: productivity/how_to_build_your_career_in_ai/phase_2_projects.md
      - Phase 3- Job: productivity/how_to_build_your_career_in_ai/phase_3_job.md
      - Make Every Day Count: productivity/how_to_build_your_career_in_ai/make_every_day_count.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2025 <a href="https://github.com/adi14041999"  target="_blank" rel="noopener">Aditya Prabhu</a>